/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112470-g721857483f-20231018"
#endif /* AVUTIL_FFVERSION_H */
